fix production

diff --git a/.github/workflows/production.yml b/.github/workflows/production.yml
--- a/.github/workflows/production.yml
+++ b/.github/workflows/production.yml
@@ -84,22 +84,49 @@ jobs:
             docker compose --env-file .env -f docker-compose.prod.yml pull
 
       # --- Deploy Production ---
-      - name: Deploy Production
+      - name: Deploy to Linode
         uses: appleboy/ssh-action@v1.2.0
         with:
           host: ${{ secrets.LINODE_HOST }}
           username: ${{ secrets.LINODE_USER }}
           key: ${{ secrets.LINODE_SSH_KEY }}
           script: |
+            set -euo pipefail
             cd /root/url-shortner-app
+            git pull
+            if [ ! -f docker-compose.prod.yml ] || [ ! -f .env ]; then
+            echo "docker-compose.prod.yml or .env missing in $(pwd)"
+            exit 1
+            fi
 
-            export BACKEND_IMAGE=${{ env.BACKEND_IMAGE }}:${{ github.sha }}
-            export FRONTEND_IMAGE=${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
+            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io \
+            -u "${{ github.actor }}" \
+            --password-stdin
 
-            docker compose --env-file .env -f docker-compose.prod.yml up -d
+            BACKEND_IMAGE="${{ env.BACKEND_IMAGE }}:${{ github.sha }}"
+            FRONTEND_IMAGE="${{ env.FRONTEND_IMAGE }}:${{ github.sha }}"
 
-            docker image prune -f
+            # Persist deployed image tags
+            if grep -q "^BACKEND_IMAGE=" .env; then
+              sed -i "s|^BACKEND_IMAGE=.*|BACKEND_IMAGE=${BACKEND_IMAGE}|" .env
+            else
+              echo "BACKEND_IMAGE=${BACKEND_IMAGE}" >> .env
+            fi
 
+            if grep -q "^FRONTEND_IMAGE=" .env; then
+              sed -i "s|^FRONTEND_IMAGE=.*|FRONTEND_IMAGE=${FRONTEND_IMAGE}|" .env
+            else
+              echo "FRONTEND_IMAGE=${FRONTEND_IMAGE}" >> .env
+            fi
+
+            echo "Deploying:"
+            grep ".*IMAGE=" .env
+
+            docker compose --env-file .env -f docker-compose.prod.yml config
+            docker compose --env-file .env -f docker-compose.prod.yml pull
+            docker compose --env-file .env -f docker-compose.prod.yml up -d --remove-orphans
+
+             docker image prune -f
       # --- Health Check ---
       - name: Wait for application
         run: sleep 20
